trigger:
  - main  # Ou a branch que você desejar monitorar

pool:
  vmImage: 'ubuntu-latest'  # Ou windows-latest, se preferir

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x.x'  # Use a versão adequada do SDK .NET
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet build --configuration Release
    displayName: 'Compilar solução'

  - script: |
      dotnet test --no-build --verbosity normal
    displayName: 'Executar testes'
