name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main  # Branch que dispara o pipeline
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build  # Aguarda o job de build ser concluído

    steps:
      - name: Deploy to Azure App Service (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NomeDoSeuAppStaging'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Deploy to Azure App Service (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NomeDoSeuAppProd'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
